python_stack/my_env/belt/apps/first_app/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views           # This line is new!
urlpatterns = [
  url(r'^$', views.index, name='index'),
  url(r'^register$',views.register, name='register'),
  url(r'login$',views.login, name='login'),
  url(r'success$', views.success, name='success'),
]

python_stack/my_env/belt/apps/second_app/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views
from ..first_app.models import users, reviews, books  # This line is new!
urlpatterns = [
  url(r'^$', views.index, name = 'index'),
  url(r'^addreview', views.addreview, name = 'addreview'),
  url(r'bookreview', views.bookreview, name="bookreview"),
  url(r'^register$',views.register, name='register'),
  url(r'^submitreview', views.submitreview, name = 'submitreview'),
]

python_stack/my_env/belt/belt/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.first_app.urls', namespace ='root')),
    url(r'^users/', include('apps.second_app.urls', namespace = 'users')),
]

python_stack/my_env/belt/apps/first_app/models.py
from __future__ import unicode_literals
from django.db import models
import re
import bcrypt
from django.db import models

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$')
NAME_REGEX = re.compile(r'^[A-Za-z]\w+$')

class usersManager(models.Manager):
    def validate_login(self, post_data):
        errors = []
        # check DB for post_data['email']
        if len(self.filter(email=post_data['email'])) > 0:
            # check this user's password
            user = self.filter(email=post_data['email'])[0]
            if not bcrypt.checkpw(post_data['password'].encode(), user.password.encode()):
                errors.append('email/password incorrect')
        else:
            errors.append('email/password incorrect')

        if errors:
            return errors
        return user

    def validate_registration(self, post_data):
        errors = []
        # check length of name fields
        if len(post_data['first_name']) < 2 or len(post_data['last_name']) < 2:
            errors.append("name fields must be at least 3 characters")
        # check length of name password
        if len(post_data['password']) < 8:
            errors.append("password must be at least 8 characters")
        # check name fields for letter characters            
        if not re.match(NAME_REGEX, post_data['first_name']) or not re.match(NAME_REGEX, post_data['last_name']):
            errors.append('name fields must be letter characters only')
        # check emailness of email
        if not re.match(EMAIL_REGEX, post_data['email']):
            errors.append("invalid email")
        # check uniqueness of email
        if len(users.objects.filter(email=post_data['email'])) > 0:
            errors.append("email already in use")
        # check password == password_confirm
        if post_data['password'] != post_data['password_confirm']:
            errors.append("passwords do not match")

        if not errors:
            # make our new user
            # hash password
            hashed = bcrypt.hashpw((post_data['password'].encode()), bcrypt.gensalt(5))

            new_user = self.create(
                first_name=post_data['first_name'],
                last_name=post_data['last_name'],
                email=post_data['email'],
                password=hashed
            )
            return new_user
        return errors

def validate_registration(self, post_data):
    errors = []
    # check length of name fields
    if len(post_data['first_name']) < 2 or len(post_data['last_name']) < 2:
        errors.append("name fields must be at least 3 characters")
    # check length of name password
    if len(post_data['password']) < 8:
        errors.append("password must be at least 8 characters")
    # check name fields for letter characters            
    if not re.match(NAME_REGEX, post_data['first_name']) or not re.match(NAME_REGEX, post_data['last_name']):
        errors.append('name fields must be letter characters only')
    # check emailness of email
    if not re.match(EMAIL_REGEX, post_data['email']):
        errors.append("invalid email")
    # check uniqueness of email
    if len(users.objects.filter(email=post_data['email'])) > 0:
        errors.append("email already in use")
    # check password == password_confirm
    if post_data['password'] != post_data['password_confirm']:
        errors.append("passwords do not match")

    if not errors:
        # make our new user
        # hash password
        hashed = bcrypt.hashpw((post_data['password'].encode()), bcrypt.gensalt(5))

        new_user = self.create(
            first_name=post_data['first_name'],
            last_name=post_data['last_name'],
            email=post_data['email'],
            password=hashed
        )
        return new_user
    return errors

class users(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    password = models.CharField(max_length=255, default ='SOME STRING')
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = usersManager()
    def __str__(self):
        return self.email

class books(models.Model):
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)


class reviews(models.Model):
    comment = models.CharField(max_length=255)
    rating = int()
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

# Create your models here.

python_stack/my_env/belt/apps/second_app/models.py
from __future__ import unicode_literals
from django.db import models
import re
import bcrypt
from django.db import models

# Create your models here.

python_stack/my_env/belt/apps/first_app/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.core.urlresolvers import reverse
from .models import users
from django.contrib import messages
# Create your views here.
def index(request):
    return render(request, "login.html")
def register(request):
    result = users.objects.validate_registration(request.POST)
    if type(result) == list:
        for err in result:
            messages.error(request, err)
        return redirect('/')
    request.session['user_id'] = result.id
    messages.success(request, "Successfully registered!!")
    users.objects.create(first_name=request.POST['first_name'], last_name=request.POST['last_name'], email=request.POST['email'] )
    print users.objects.all()
    return redirect("/success")

def login(request):
    result = users.objects.validate_login(request.POST)
    if type(result) == list:
        for err in result:
            messages.error(request, err)
        return redirect('/')
    request.session['user_id'] = result.id
    messages.success(request, "Successfully logged in!")
    return redirect('/success')

def success(request):
    try:
        request.session['user_id']
    except KeyError:
        return redirect('/')
    context = {
        'user': users.objects.get(id=request.session['user_id'])
    }
    return render(request, 'addbook.html', context)

python_stack/my_env/belt/apps/second_app/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.core.urlresolvers import reverse
from ..first_app.models import users, reviews, books
from django.contrib import messages

def index(request):
    return render(request, "login.html")

def bookreview(request):
    return render(request, "bookreviews.html")

def addreview(request):
    # print request.POST['book_title']
    # print request.POST['author']
    # print request.POST['review']
    # print request.POST['number']
    # books.objects.create(title=request.POST['book_title'], author=request.POST['author'])
    # reviews.objects.create(comment = request.POST['review'], rating = 3)
    return render(request, 'addreview.html')
def submitreview(request):
    print request.POST['book_title']
    print request.POST['author']
    print request.POST['review']
    print request.POST['number']
    return render(request, 'addreview.html')

def register(request):
    print request.POST['review']
    return render(request, 'userreview.html')

# Create your views here.

python_stack/my_env/belt/apps/first_app/templates/addbook.html
<!DOCTYPE html>
<html lang='en'>
    <head>
        <meta charset="utf-8">
        <title>Add Review</title>
    </head>
    <body>
        <div id="wrapper">
            <!-- need the add book button to go to the likes.html page -->
            <!-- need the logout button to return you to the login .html page -->
            <a href="{% url 'users:addreview' %}">Add Book and Review</a>
            <a href="{% url 'users:index' %}">Logout</a>
            <h1>Welcome,{{ user.first_name }}!</h1>
            {% if messages %}
            <div class="messages">
                {% for message in messages %}
                    <P>{{ message }}</p>
                {% endfor %}
            </div>
        {% endif %}
        <div class="recent">
            <h3>Recent Book Reviews</h3>
        </div>
        <div class="other">
            <h3>Other Books With Reviews!</h3>
        </div>
        </div>
    </body>
</html>

python_stack/my_env/belt/apps/first_app/templates/login.html
<!DOCTYPE html>
<html lang='en'>
    <head>
        <meta charset="utf-8">
        <title>Login/Register</title>
    </head>
</head>
<body>
  {% if messages %}
  <div class="messages">
    {% for message in messages %}
    <p>{{ message }}</p>
    {% endfor %}
  </div>
  {% endif %}
  <form action="register" method='POST'>
    {% csrf_token %}
  <table>
    <tr>
      <td>Registration</td>
    </tr>
    <tr>
      <td>First Name: </td>
      <td><input type="text" name="first_name" value=""></td>
    </tr>
    <tr>
      <td>Last Name: </td>
      <td><input type="text" name="last_name" value=""></td>
    </tr>
    <tr>
      <td>Email: </td>
      <td><input type="text" name="email" value=""></td>
    </tr>
    <tr>
      <td>Password: </td>
      <td><input type="text" name="password" value=""></td>
    </tr>
    <tr>
      <td>confirm pw: </td>
      <td><input type="text" name="password_confirm" value=""></td>
    </tr>
  </table>
  
  <input type="submit" value="Submit">
  </form>
<form action="login" method="POST">
  {% csrf_token %}
  <table>
    <tr>
      <td>Login</td>
    </tr>
    <tr>
      <td>Email: </td>
      <td><input type="text" name="email" value=""></td>
    </tr>
    <tr>
      <td>Password: </td>
      <td><input type="text" name="password" value=""></td>
    </tr>
  </table>
    <input type="submit" value="Submit">
  </form>
</body>
</html>

python_stack/my_env/belt/apps/second_app/templates/addreview.html
<!DOCTYPE html>
<html lang='en'>
    <head>
        <meta charset="utf-8">
        <title>Reviews</title>
        <style>
        </style>
        </head>
        <body>
    </head>
    <body>
        <div id="wrapper">
            <a href="{% url 'users:bookreview' %}">Home</a>
            <a href="{% url 'users:index' %}">Logout</a>
            <h1>Add a New Book Title and a Review:</h1>
            <div id="reviews">
                <p>Book Title:</p>
                <form name="ratings" action="submitreview" method="POST">
                        {% csrf_token %}
                        <!-- need to have the submit button on this page direct me to the bookreviews.html page -->
                <input type="text box" name="book_title">
                <p>Choose from List:</p>
                <select>
                    <option value="{{author_name}}">author_name</option>
                    <option value="{{author_name}}">author_name</opstion>"
                </select>
                <p>Or add new author:</p>
                <input type="text box" name="author">
                <h3>Review:</h3>
                <input type="text box" name="review">
                <p>Rating:</p>
                <select name="number">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
                <input type="submit" value="Add Book and Review">
            </form>
            </div>
        </div>
    </body>
</html>

python_stack/my_env/belt/apps/second_app/templates/bookreviews.html
<!DOCTYPE html>
<html lang='en'>
    <head>
        <meta charset="utf-8">
        <title>Add Book and Review</title>
    </head>
    <body>
        <div id="wrapper">
            <a href="{% url 'users:addreview' %}">Add Book and Review</a>
            <a href="{% url 'users:index' %}">logout</a>
            <h1>{{ blank }}</h1>
            <!-- need to have the home button go to the addbook.html page -->
            <!-- need to have the logout button go to the login .html page -->
            <h3>Authors: {{ blank }}</h3>
            <div id="reviews">
                <h3>Reviews:</h3>
            </div>
            <div id="add_review">
                <form action="register" method='POST'>
                        {% csrf_token %}
                    <h3>Add a Review:</h3>
                    <input type="text box" name="review">
                        <select>
                            <option name="number" value="1">1</option>
                            <option name="number" value="2">2</option>
                            <option name="number" value="3">3</option>
                            <option name="number" value="4">4</option>
                            <option name="number" value="5">5</option>                           
                        </select>
                    <input type="submit" value="Submit this Review!">
                </form>
            </div>
        </div>
    </body>
</html>

python_stack/my_env/belt/apps/second_app/templates/userreview.html
<!DOCTYPE html>
<html lang='en'>
    <head>
        <meta charset="utf-8">
        <title>User reviews</title>
    </head>
    <body>
        <div id="wrapper">
            <!-- need to have the home button go to the addbook.html page -->
            <!-- need to have the add book and review button go to the like.html page -->
            <!-- need to have the logout button go to the login .html page -->
            <h1>User Alias: Jessie!</h1>
            <a href="{% url 'users:bookreview' %}">Home</a>
            <a href="{% url 'users:addreview' %}">Add Book and Review</a>
            <a href="{% url 'users:index' %}">Logout</a>
            <p>User Alias:{{ blank }}</p>
            <p>Name: {{ blank }}</p>
            <p>Email: {blank }}</p>
            <p>Total Reviews:{{ blank }}</p>
            <h3>Posted Reviews in the following books:</h3>
        </div>
    </body>
</html>