python_stack/my_env/wish_list/apps/first_app/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views           # This line is new!
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'register$',views.register, name='create'),
    url(r'login$',views.login, name='login'),
    url(r'success$', views.success, name='success'),
    url(r'^addeditem$', views.addeditem, name = 'addeditem'),
    url(r'^newwish$', views.newwish, name='newwish'),
]

python_stack/my_env/wish_list/apps/second_app/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views
from ..first_app.models import users, items    # This line is new!
urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^additem$', views.additem, name = 'additem'),
]

python_stack/my_env/wish_list/wish_list/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.first_app.urls', namespace ='root')),
    url(r'^users', include('apps.second_app.urls', namespace='users')),
]

python_stack/my_env/wish_list/apps/first_app/models.py
from __future__ import unicode_literals
from django.db import models
import re
import bcrypt
from django.db import models
from datetime import date

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$')
NAME_REGEX = re.compile(r'^[A-Za-z]\w+$')

class usersManager(models.Manager):
    def validate_login(self, post_data):
        errors = []
        # check DB for post_data['email']
        if len(self.filter(email=post_data['email'])) > 0:
            # check this user's password
            user = self.filter(email=post_data['email'])[0]
            if not bcrypt.checkpw(post_data['password'].encode(), user.password.encode()):
                errors.append('email/password incorrect')
        else:
            errors.append('email/password incorrect')

        if errors:
            return errors
        return user

    def validate_registration(self, post_data):
        errors = []
        # check length of name fields
        if len(post_data['first_name']) < 3 or len(post_data['last_name']) < 3:
            errors.append("name fields must be at least 3 characters")
        # check length of name password
        if len(post_data['password']) < 8:
            errors.append("password must be at least 8 characters")
        # check name fields for letter characters            
        if not re.match(NAME_REGEX, post_data['first_name']) or not re.match(NAME_REGEX, post_data['last_name']):
            errors.append('name fields must be letter characters only')
        # check emailness of email
        if not re.match(EMAIL_REGEX, post_data['email']):
            errors.append("invalid email")
        # check uniqueness of email
        if len(users.objects.filter(email=post_data['email'])) > 0:
            errors.append("email already in use")
        # check password == password_confirm
        if post_data['password'] != post_data['password_confirm']:
            errors.append("passwords do not match")

        if not errors:
            # make our new user
            # hash password
            hashed = bcrypt.hashpw((post_data['password'].encode()), bcrypt.gensalt(5))

            new_user = self.create(
                first_name=post_data['first_name'],
                last_name=post_data['last_name'],
                email=post_data['email'],
                password=hashed
            )
            return new_user
        return errors

class users(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    password = models.CharField(max_length=255, default ='SOME STRING')
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = usersManager()
    def __str__(self):
        return self.email

class items(models.Model):
    name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add = True)
    wishes = models.ManyToManyField(users, related_name="products")

python_stack/my_env/wish_list/apps/second_app/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

python_stack/my_env/wish_list/apps/first_app/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from .models import users, items
from django.contrib import messages
# Create your views here.
def index(request):
    return render(request, "login_reg.html")
def register(request):
    result = users.objects.validate_registration(request.POST)
    if type(result) == list:
        for err in result:
            messages.error(request, err)
        return redirect('/')
    request.session['user_id'] = result.id
    messages.success(request, "Logged in!!")
    users.objects.create(first_name=request.POST['first_name'], last_name=request.POST['last_name'], email=request.POST['email'] )
    return redirect("/success")

def login(request):
    result = users.objects.validate_login(request.POST)
    if type(result) == list:
        for err in result:
            messages.error(request, err)
        return redirect('/')
    request.session['user_id'] = result.id
    messages.success(request, "Successfully logged in!")
    return redirect('/success')

def success(request):
    try:
        request.session['user_id']
    except KeyError:
        return redirect('/')
    context = {
        'user': users.objects.get(id=request.session['user_id']),
        'all_users': users.objects.all().values(),
        'item': items.objects.all().values(),
    }
    return render(request, 'dash.html', context)
def addeditem(request):
    print request.POST['item']
    items.objects.create(name=request.POST['item'])
    print items.objects.all()
    return render(request, "dash.html")
def newwish(request):
    context = {
        "item" : items.objects.all().values()
    }
    return render(request, 'newwish.html', context)

python_stack/my_env/wish_list/apps/second_app/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from ..first_app.models import users, items
from django.contrib import messages
# Create your views here.
def index(request):
    return render(request, "indexfirst.html")
def additem(request):
    return render(request, "userwishes.html")

python_stack/my_env/wish_list/apps/first_app/templates/dash.html
<!DOCTYPE html>
<html lang='en'>
    <head>
        <meta charset="utf-8">
        <title>Add Review</title>
        {% load static %}
    </head>
    <body>
        <div id="wrapper">
            <a href="{% url 'root:index' %}">Logout</a>
            <h1>Welcome,{{ user.first_name }}!</h1>
            {% if messages %}
            <div class="messages">
                {% for message in messages %}
                    <P>{{ message }}</p>
                {% endfor %}
            </div>
        {% endif %}
        <div class="recent">
            <h3>Your Wish List!</h3>
            <table>
                <tr>
                    <td>Item</td>
                    <td>Added By</td>
                    <td>Date Added</td>
                    <td>Action</td>
                </tr>
                {% for users in all_users %}     
                <tr>
                    <td>{{ users.first_name }} {{ users.last_name }}</td>
                    <td>{{ users.email }}</td>
                    <td>{{ users.created_at }}</td>
                    <td>
                        <a href="">Remove from my Wishlist</a>
                        <a href="">Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <div class="other">
            <h3>Other Users wish lists!</h3>
            <table>
                    <tr>
                            <td>Item</td>
                            <td>Added By</td>
                            <td>Date Added</td>
                            <td>Action</td>
                        </tr>
                    {% for items in item %}     
                    <tr>
                        <td>{{ items.id }}</td>
                        <td><a href="{% url 'root:newwish' %}">{{ items.name }}</a></td>
                        <td>
                            <a href="">Add to my Wishlist!</a>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
        </div>
        <div id="additem">
                <a href="{% url 'users:additem' %}">Add Item</a>
        </div>
        </div>
    </body>
</html>

python_stack/my_env/wish_list/apps/first_app/templates/login_reg.html
<!DOCTYPE html>
<html lang='en'>
  <head>
    <meta charset="utf-8">
    <title>Login and Registration</title>
  </head>
  <body>
    {% if messages %}
    <div class="messages">
      {% for message in messages %}
      <p>{{ message }}</p>
      {% endfor %}
    </div>
    {% endif %}
    <form action="register" method='POST'>
      {% csrf_token %}
    <table>
      <tr>
        <td>Registration</td>
      </tr>
      <tr>
        <td>First Name: </td>
        <td><input type="text" name="first_name" value=""></td>
      </tr>
      <tr>
        <td>Last Name: </td>
        <td><input type="text" name="last_name" value=""></td>
      </tr>
      <tr>
        <td>Email: </td>
        <td><input type="text" name="email" value=""></td>
      </tr>
      <tr>
        <td>Password: </td>
        <td><input type="text" name="password" value=""></td>
      </tr>
      <tr>
        <td>confirm pw: </td>
        <td><input type="text" name="password_confirm" value=""></td>
      </tr>
    </table>
    <input type="submit" value="Submit">
    </form>
  <form action="login" method="POST">
    {% csrf_token %}
    <table>
      <tr>
        <td>Login</td>
      </tr>
      <tr>
        <td>Email: </td>
        <td><input type="text" name="email" value=""></td>
      </tr>
      <tr>
        <td>Password: </td>
        <td><input type="text" name="password" value=""></td>
      </tr>
    </table>
      <input type="submit" value="Submit">
    </form>
  </body>
</html>

python_stack/my_env/wish_list/apps/second_app/templates/newwish.html
<!DOCTYPE html>
<html lang='en'>
    <head>
        <meta charset="utf-8">
        <title>Items</title>
    </head>
    <body>
        <a href="{% url 'root:success' %}">Home</a>
        <a href="{% url 'root:index' %}">Logout</a>
        {% for items in item %}
        <h1> {{ items.name }}</h1>
        {% endfor %}
        <h3>User List of who added this item to their wishlist!!</h3>
        <h4>{{Blank}}Needs to be list of users inserted!!</h4>
    </body>
</html>

python_stack/my_env/wish_list/apps/second_app/templates/userwishes.html
<!DOCTYPE html>
<html lang='en'>
    <head>
        <meta charset="utf-8">
        <title>Items</title>
    </head>
    <body>
        <h1>Create a New Wish List Item!!!</h1>
            <h4>Item/Product</h4>
            <form action="addeditem" method='POST'>
                {% csrf_token %}
                <input type="text box" name="item">
                <input type="submit" value="Add">
            </form>
            <a href="{% url 'root:success' %}">Home</a>
            <a href="{% url 'root:index' %}">Logout</a>
    </body>
</html>